"""Run daily watchlist research and upsert clarity scores.

This script is the 20:00 KST runner that consumes the watchlist generated by
build_watchlist.py. It writes local reports and upserts rows into
db/watchlist.duckdb / llm_scores.
"""
from __future__ import annotations

import argparse
import html
import json
import os
import re
import subprocess
import sys
import xml.etree.ElementTree as ET
from dataclasses import dataclass
from datetime import datetime
from html.parser import HTMLParser
from pathlib import Path
from urllib.parse import urljoin

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

import duckdb
import requests
from dotenv import load_dotenv

ROOT = Path(__file__).resolve().parents[2]
ETL_DIR = Path(__file__).resolve().parents[1]
ENV_PATH = ROOT / ".env"
DEFAULT_WATCHLIST_DB = ETL_DIR / "db" / "watchlist.duckdb"
DEFAULT_KRX_DB = ETL_DIR / "db" / "krx_ohlcv.duckdb"
DEFAULT_REPORTS_DIR = Path(r"C:\Users\mullu\.openclaw\workspace\reports")

HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0 Safari/537.36"
    )
}

CREATE_LLM_SCORES = """
CREATE TABLE IF NOT EXISTS llm_scores (
    date           VARCHAR,
    ticker         VARCHAR,
    name           VARCHAR,
    ratio          DOUBLE,
    today_volume   BIGINT,
    avg5_volume    BIGINT,
    trading_value  BIGINT,
    close          INTEGER,
    score          INTEGER,
    category       VARCHAR,
    reason_summary TEXT,
    final_opinion  TEXT,
    evidence_board TEXT,
    evidence_news  TEXT,
    evidence_web   TEXT,
    sources        TEXT,
    PRIMARY KEY (date, ticker)
)
"""

CATEGORY_RULES = [
    ("개별재료", ["공시", "실적", "계약", "수주", "허가", "특허", "인수", "합병", "m&a", "신제품"]),
    ("섹터·테마", ["테마", "관련주", "반도체", "바이오", "로봇", "ai", "2차전지", "방산", "조선", "hbm", "전력반도체"]),
    ("정책·제도", ["정책", "규제", "법안", "정부", "대통령", "국회", "관세"]),
    ("수급·유동성", ["외국인", "기관", "프로그램", "공매도", "숏커버", "거래대금", "수급", "투자주의", "투자경고"]),
    ("기술적 요인", ["신고가", "상한가", "하한가", "vi", "급등", "돌파", "차트"]),
    ("이벤트·일정", ["실적발표", "주총", "권리락", "리밸런싱", "상장", "재상장"]),
    ("구조변경 이슈", ["액면분할", "액면병합", "최대주주", "유상증자", "감자", "cb", "bw"]),
    ("소문·커뮤니티 주도", ["루머", "카더라", "찌라시", "종토방", "작전", "세력"]),
]

POSITIVE_BOARD_KEYWORDS = [
    "상한가", "강하", "돌파", "매수", "저가", "호재", "대박", "급등", "가자",
    "수익", "핵심", "개발", "기대", "삼성", "실적", "재료", "신고가",
]
NEGATIVE_BOARD_KEYWORDS = [
    "폭락", "주의", "공매", "마이너스", "하락", "물림", "손절", "불안",
    "위험", "투주", "투경", "세력", "끝", "매도", "고점",
]
RUMOR_BOARD_KEYWORDS = ["카더라", "사라", "검토", "인수", "루머", "찌라시", "작전", "세력"]


@dataclass
class LinkItem:
    title: str
    link: str | None = None
    description: str | None = None


class AnchorParser(HTMLParser):
    def __init__(self, href_pattern: str | None = None) -> None:
        super().__init__()
        self.href_pattern = href_pattern
        self._current_href: str | None = None
        self._current_text: list[str] = []
        self.items: list[LinkItem] = []

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        if tag.lower() != "a":
            return
        attrs_dict = dict(attrs)
        href = attrs_dict.get("href") or ""
        if self.href_pattern and not re.search(self.href_pattern, href):
            return
        self._current_href = href
        self._current_text = []

    def handle_data(self, data: str) -> None:
        if self._current_href is not None:
            self._current_text.append(data)

    def handle_endtag(self, tag: str) -> None:
        if tag.lower() != "a" or self._current_href is None:
            return
        title = clean_text(" ".join(self._current_text))
        if title:
            self.items.append(LinkItem(title=title, link=self._current_href))
        self._current_href = None
        self._current_text = []


class TextExtractor(HTMLParser):
    def __init__(self) -> None:
        super().__init__()
        self.parts: list[str] = []
        self._skip_depth = 0

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        if tag.lower() in {"script", "style", "noscript"}:
            self._skip_depth += 1

    def handle_endtag(self, tag: str) -> None:
        if tag.lower() in {"script", "style", "noscript"} and self._skip_depth:
            self._skip_depth -= 1

    def handle_data(self, data: str) -> None:
        if not self._skip_depth:
            self.parts.append(data)

    def text(self) -> str:
        return clean_text(" ".join(self.parts))


def clean_text(value: str) -> str:
    value = html.unescape(re.sub(r"<[^>]+>", " ", value or ""))
    value = re.sub(r"\s*\[\d+\]\s*$", "", value)
    return " ".join(value.split())


def html_text(value: str) -> str:
    parser = TextExtractor()
    parser.feed(value or "")
    return parser.text()


def compact_join(parts: list[str], sep: str = ", ") -> str:
    return sep.join(part for part in parts if part)


def usable_board_description(value: str | None) -> bool:
    if not value:
        return False
    noise = ("Npay 증권", "메인 메뉴", "자동완성", "@code@", "시가총액", "호가10단계")
    return not any(marker in value for marker in noise)


def unique_items(items: list[LinkItem], limit: int) -> list[LinkItem]:
    seen: set[str] = set()
    out: list[LinkItem] = []
    for item in items:
        key = clean_text(item.title)
        if not key or key in seen:
            continue
        seen.add(key)
        out.append(item)
        if len(out) >= limit:
            break
    return out


def request_text(url: str, **kwargs) -> str:
    res = requests.get(url, headers=HEADERS, timeout=kwargs.pop("timeout", 15), **kwargs)
    res.raise_for_status()
    if not res.encoding or res.encoding.lower() in {"iso-8859-1", "ascii"}:
        res.encoding = res.apparent_encoding or "utf-8"
    return res.text


def fetch_board_detail(link: str | None, title: str) -> str | None:
    if not link:
        return None
    try:
        text = html_text(request_text(link, timeout=10))
    except Exception:
        return None
    if not text:
        return None
    title_pos = text.find(title)
    if title_pos >= 0:
        text = text[title_pos + len(title):]
    for pattern in (
        r"네이버페이.*",
        r"로그인.*",
        r"증권 고객센터.*",
        r"Copyright.*",
    ):
        text = re.sub(pattern, " ", text, flags=re.I)
    text = clean_text(text)
    for marker in ("투자정보", "목록 이전", "목록 다음", "이전 글", "다음 글"):
        if marker in text:
            text = text.split(marker, 1)[0].strip()
    return text[:260] if text else None


def fetch_board(ticker: str, limit: int = 8) -> list[LinkItem]:
    try:
        text = request_text(f"https://finance.naver.com/item/board.naver?code={ticker}")
        parser = AnchorParser(r"/item/board_read\.naver")
        parser.feed(text)
        for item in parser.items:
            item.link = urljoin("https://finance.naver.com", item.link or "")
        items = unique_items(parser.items, limit)
        for item in items[:5]:
            item.description = fetch_board_detail(item.link, item.title)
        return items
    except Exception as exc:
        return [LinkItem(title=f"조사 실패: {exc}")]


def fetch_naver_stock_news(ticker: str, limit: int = 5) -> list[LinkItem]:
    try:
        text = request_text(f"https://finance.naver.com/item/news_news.naver?code={ticker}&page=1")
        parser = AnchorParser(r"/item/news_read\.naver")
        parser.feed(text)
        for item in parser.items:
            item.link = urljoin("https://finance.naver.com", item.link or "")
        return unique_items(parser.items, limit)
    except Exception:
        return []


def fetch_google_news(query: str, limit: int = 5) -> list[LinkItem]:
    try:
        text = request_text(
            "https://news.google.com/rss/search",
            params={"q": query, "hl": "ko", "gl": "KR", "ceid": "KR:ko"},
            timeout=20,
        )
        root = ET.fromstring(text.encode("utf-8"))
        items = []
        for node in root.findall(".//item"):
            title = clean_text(node.findtext("title") or "")
            link = clean_text(node.findtext("link") or "")
            if title:
                items.append(LinkItem(title=title, link=link))
        return unique_items(items, limit)
    except Exception as exc:
        return [LinkItem(title=f"뉴스 조사 실패: {exc}")]


def fetch_web(query: str, limit: int = 5) -> list[LinkItem]:
    try:
        text = request_text(
            "https://news.google.com/rss/search",
            params={"q": query, "hl": "ko", "gl": "KR", "ceid": "KR:ko"},
            timeout=20,
        )
        root = ET.fromstring(text.encode("utf-8"))
        items = []
        for node in root.findall(".//item"):
            title = clean_text(node.findtext("title") or "")
            link = clean_text(node.findtext("link") or "")
            if title:
                items.append(LinkItem(title=title, link=link))
        return unique_items(items, limit)
    except Exception as exc:
        return [LinkItem(title=f"웹 조사 실패: {exc}")]


def ticker_name(ticker: str) -> str:
    try:
        text = request_text(f"https://finance.naver.com/item/main.naver?code={ticker}")
        match = re.search(r"<title>\s*(.*?)\s*[:：]", text, re.I | re.S)
        if match:
            return clean_text(match.group(1))
    except Exception:
        pass
    return ticker


def relevant_items(items: list[LinkItem], name: str, ticker: str, limit: int, fallback: bool = True) -> list[LinkItem]:
    tokens = {name.lower(), ticker.lower()}
    out = []
    for item in items:
        haystack = f"{item.title} {item.description or ''}".lower()
        if any(token and token in haystack for token in tokens):
            out.append(item)
    return unique_items(out or (items if fallback else []), limit)


def normalize_date(value: str | None) -> str | None:
    if not value:
        return None
    digits = re.sub(r"\D", "", value)
    if len(digits) != 8:
        raise ValueError(f"date must be YYYYMMDD or YYYY-MM-DD: {value}")
    return digits


def dashed_date(yyyymmdd: str) -> str:
    return f"{yyyymmdd[:4]}-{yyyymmdd[4:6]}-{yyyymmdd[6:]}"


def load_paths() -> tuple[Path, Path, Path]:
    load_dotenv(ENV_PATH)
    wl = Path(os.environ.get("WATCHLIST_DB_PATH") or DEFAULT_WATCHLIST_DB)
    krx = Path(os.environ.get("KRX_DB_PATH") or DEFAULT_KRX_DB)
    reports = Path(os.environ.get("REPORTS_DIR") or DEFAULT_REPORTS_DIR)
    if not wl.is_absolute():
        wl = (ROOT / wl).resolve()
    if not krx.is_absolute():
        krx = (ROOT / krx).resolve()
    return wl, krx, reports


def run_build_watchlist(date: str | None, force: bool) -> str | None:
    cmd = [sys.executable, str(Path(__file__).with_name("build_watchlist.py"))]
    if date:
        cmd += ["--date", date]
    if force:
        cmd.append("--force")
    proc = subprocess.run(
        cmd,
        cwd=str(ETL_DIR),
        check=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
    )
    if proc.stdout:
        print(proc.stdout, end="" if proc.stdout.endswith("\n") else "\n")
    match = re.search(r"\[watchlist\]\s+target=(\d{8})", proc.stdout or "")
    return match.group(1) if match else None


def latest_watchlist_date(watchlist_db: Path) -> str:
    with duckdb.connect(str(watchlist_db), read_only=True) as con:
        row = con.execute("SELECT max(date) FROM watchlist").fetchone()
    if not row or not row[0]:
        raise RuntimeError("watchlist table has no dates")
    return str(row[0])


def load_watchlist(watchlist_db: Path, date: str, limit: int | None) -> list[str]:
    sql = "SELECT stock_code FROM watchlist WHERE date = ? ORDER BY stock_code"
    if limit:
        sql += f" LIMIT {int(limit)}"
    with duckdb.connect(str(watchlist_db), read_only=True) as con:
        return [r[0] for r in con.execute(sql, [date]).fetchall()]


def load_market_metrics(
    krx_db: Path,
    watchlist_db: Path,
    date: str,
    tickers: list[str],
) -> dict[str, dict]:
    if not tickers:
        return {}
    placeholders = ",".join(["?"] * len(tickers))
    with duckdb.connect(str(krx_db), read_only=True) as con:
        today_rows = con.execute(
            f"""
            SELECT ticker, close, volume, trading_value
            FROM ohlcv
            WHERE date = ? AND ticker IN ({placeholders})
            """,
            [date, *tickers],
        ).fetchall()
        avg_rows = con.execute(
            f"""
            WITH recent AS (
                SELECT ticker, volume,
                       row_number() OVER (PARTITION BY ticker ORDER BY date DESC) AS rn
                FROM ohlcv
                WHERE date < ? AND ticker IN ({placeholders})
            )
            SELECT ticker, avg(volume)::BIGINT AS avg5_volume
            FROM recent
            WHERE rn <= 5
            GROUP BY ticker
            """,
            [date, *tickers],
        ).fetchall()
    metrics = {
        ticker: {"close": close, "today_volume": volume, "trading_value": trading_value}
        for ticker, close, volume, trading_value in today_rows
    }
    for ticker, avg5 in avg_rows:
        metrics.setdefault(ticker, {})["avg5_volume"] = avg5
    missing_today = [
        ticker
        for ticker in tickers
        if not metrics.get(ticker, {}).get("today_volume")
        or not metrics.get(ticker, {}).get("close")
    ]
    if missing_today:
        intraday_placeholders = ",".join(["?"] * len(missing_today))
        try:
            with duckdb.connect(str(watchlist_db), read_only=True) as con:
                intraday_rows = con.execute(
                    f"""
                    SELECT ticker, close, volume
                    FROM intraday_ranking
                    WHERE date = ? AND ticker IN ({intraday_placeholders})
                    """,
                    [date, *missing_today],
                ).fetchall()
        except duckdb.CatalogException:
            intraday_rows = []
        for ticker, close, volume in intraday_rows:
            vals = metrics.setdefault(ticker, {})
            vals["close"] = close
            vals["today_volume"] = volume
            if close is not None and volume is not None:
                vals["trading_value"] = int(close) * int(volume)
    for ticker, vals in metrics.items():
        today = vals.get("today_volume") or 0
        avg5 = vals.get("avg5_volume") or 0
        vals["ratio"] = round(today / avg5, 2) if avg5 else None
    return metrics


def classify(text: str) -> str:
    lowered = text.lower()
    hits = []
    for category, keywords in CATEGORY_RULES:
        if any(keyword.lower() in lowered for keyword in keywords):
            hits.append(category)
    uniq = list(dict.fromkeys(hits))
    if not uniq:
        return "원인불명"
    if len(uniq) >= 2:
        return "복합요인"
    return uniq[0]


def source_is_real(items: list[LinkItem]) -> bool:
    return any(item.title and "조사 실패" not in item.title and "뉴스 조사 실패" not in item.title and "웹 조사 실패" not in item.title for item in items)


def clarity_score(board: list[LinkItem], news: list[LinkItem], web: list[LinkItem], category: str, ratio: float | None) -> int:
    sources = sum([source_is_real(board), source_is_real(news), source_is_real(web)])
    score = sources * 22
    if category in {"개별재료", "정책·제도", "구조변경 이슈", "이벤트·일정"}:
        score += 18
    elif category in {"복합요인", "섹터·테마", "수급·유동성", "기술적 요인"}:
        score += 10
    elif category == "소문·커뮤니티 주도":
        score -= 5
    else:
        score -= 12
    if ratio and ratio >= 10:
        score += 4
    return max(0, min(100, score))


def summarize_items(label: str, items: list[LinkItem], count: int = 3) -> str:
    real = [item for item in items if source_is_real([item])]
    if not real:
        return f"{label}: 확인 가능한 근거 없음"
    titles = "; ".join(item.title for item in real[:count])
    return f"{label}: {titles}"


def board_profile(board: list[LinkItem]) -> dict:
    real = [item for item in board if source_is_real([item])]
    text = " ".join(f"{item.title} {item.description or ''}" for item in real).lower()
    positive = sum(1 for keyword in POSITIVE_BOARD_KEYWORDS if keyword.lower() in text)
    negative = sum(1 for keyword in NEGATIVE_BOARD_KEYWORDS if keyword.lower() in text)
    rumor = sum(1 for keyword in RUMOR_BOARD_KEYWORDS if keyword.lower() in text)
    if not real:
        tone = "확인불가"
        summary = "확인 가능한 최신 종토방 근거가 부족함"
    elif positive > negative and positive >= rumor:
        tone = "기대 우세"
        summary = "호재·테마 기대와 상승 지속 기대가 우세"
    elif negative > positive:
        tone = "경계 우세"
        summary = "단기 과열, 하락 우려, 수급 의심 발언이 우세"
    elif rumor:
        tone = "루머 혼재"
        summary = "인수·검토·세력성 표현 등 확인 필요 발언이 혼재"
    else:
        tone = "혼조"
        summary = "뚜렷한 한 방향보다 단기 수급성 반응이 혼재"
    snippets = []
    for item in real[:3]:
        if usable_board_description(item.description) and not item.description.startswith("조회 "):
            snippets.append(f"{item.title}({item.description[:80]})")
        else:
            snippets.append(item.title)
    return {
        "tone": tone,
        "summary": summary,
        "positive": positive,
        "negative": negative,
        "rumor": rumor,
        "snippets": snippets,
    }


def summarize_board(board: list[LinkItem]) -> str:
    profile = board_profile(board)
    snippets = "; ".join(profile["snippets"]) if profile["snippets"] else "샘플 없음"
    return (
        f"종토방: {profile['tone']} - {profile['summary']} "
        f"(긍정 키워드 {profile['positive']}, 경계 키워드 {profile['negative']}, 루머성 키워드 {profile['rumor']}). "
        f"주요 언급: {snippets}"
    )


def cause_summary(category: str, board: list[LinkItem], news: list[LinkItem], web: list[LinkItem], metrics: dict) -> str:
    profile = board_profile(board)
    news_titles = [item.title for item in news if source_is_real([item])][:2]
    web_titles = [item.title for item in web if source_is_real([item])][:2]
    ratio = metrics.get("ratio")
    ratio_text = f"거래량은 5일 평균 대비 {ratio}배" if ratio is not None else "거래량 배율은 산출 불가"
    evidence = compact_join(news_titles + web_titles, "; ")
    if category == "원인불명":
        base = "급등 원인 후보: watchlist 신규 진입은 확인됐지만 당일 신규 확정 재료는 약함"
    elif category == "복합요인":
        base = "급등 원인 후보: 뉴스성 재료, 테마 기대, 종토방 수급 반응이 결합된 복합 요인"
    else:
        base = f"급등 원인 후보: {category} 관련 재료"
    if evidence:
        base += f". 확인 근거: {evidence}"
    base += f". 종토방 분위기: {profile['tone']}({profile['summary']}). {ratio_text}."
    return base


def final_opinion_text(category: str, score: int, reason: str, board: list[LinkItem], metrics: dict) -> str:
    profile = board_profile(board)
    value = metrics.get("trading_value")
    value_text = f"거래대금 {value:,}원" if value is not None else "거래대금 N/A"
    if score >= 80:
        clarity = "세 소스가 비교적 같은 방향을 가리켜 원인 명확성이 높다"
    elif score >= 60:
        clarity = "설명 가능한 재료는 있으나 단일 확정 재료로 보기엔 혼재돼 있다"
    else:
        clarity = "원인 근거가 약하거나 커뮤니티·수급성 해석 비중이 크다"
    return (
        f"{reason} {value_text}. 종토방은 {profile['tone']}이며, "
        f"{clarity}. 점수 {score}점은 상승 확률이 아니라 급등 원인 명확성 점수다."
    )


def item_links(items: list[LinkItem]) -> list[str]:
    return [item.link for item in items if item.link and item.link.startswith("http")]


def research_one(date: str, ticker: str, metrics: dict) -> dict:
    name = ticker_name(ticker)
    board = fetch_board(ticker)
    naver_news = fetch_naver_stock_news(ticker)
    google_news = fetch_google_news(f"{name} {ticker} 주식")
    news = relevant_items(naver_news + google_news, name, ticker, 6)
    web = relevant_items(fetch_web(f"{name} {ticker} 급등 원인 공시"), name, ticker, 5, fallback=False)

    combined = " ".join(
        [f"{item.title} {item.description or ''}" for item in board]
        + [item.title for item in news]
        + [f"{item.title} {item.description or ''}" for item in web]
    )
    category = classify(combined)
    ratio = metrics.get("ratio")
    score = clarity_score(board, news, web, category, ratio)
    evidence_board = summarize_board(board)
    evidence_news = summarize_items("뉴스", news)
    evidence_web = summarize_items("웹", web)
    reason = cause_summary(category, board, news, web, metrics)
    final = final_opinion_text(category, score, reason, board, metrics)
    sources = sorted(set(
        [f"https://finance.naver.com/item/board.naver?code={ticker}"]
        + item_links(news)
        + item_links(web)
    ))

    return {
        "date": dashed_date(date),
        "ticker": ticker,
        "name": name,
        "ratio": ratio,
        "today_volume": metrics.get("today_volume"),
        "avg5_volume": metrics.get("avg5_volume"),
        "trading_value": metrics.get("trading_value"),
        "close": metrics.get("close"),
        "score": score,
        "category": category,
        "reason_summary": reason,
        "final_opinion": final,
        "evidence_board": evidence_board,
        "evidence_news": evidence_news,
        "evidence_web": evidence_web,
        "sources": sources,
        "raw": {
            "board": [item.__dict__ for item in board],
            "news": [item.__dict__ for item in news],
            "web": [item.__dict__ for item in web],
        },
    }


def upsert_scores(watchlist_db: Path, rows: list[dict]) -> None:
    values = []
    for row in rows:
        values.append(
            (
                row["date"].replace("-", ""),
                row["ticker"],
                row["name"],
                row["ratio"],
                row["today_volume"],
                row["avg5_volume"],
                row["trading_value"],
                row["close"],
                row["score"],
                row["category"],
                row["reason_summary"],
                row["final_opinion"],
                row["evidence_board"],
                row["evidence_news"],
                row["evidence_web"],
                json.dumps(row["sources"], ensure_ascii=False),
            )
        )
    with duckdb.connect(str(watchlist_db)) as con:
        con.execute(CREATE_LLM_SCORES)
        if values:
            con.executemany(
                "INSERT OR REPLACE INTO llm_scores VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
                values,
            )


def write_reports(reports_dir: Path, date: str, rows: list[dict], build_status: str, watchlist_db: Path) -> tuple[Path, Path]:
    reports_dir.mkdir(parents=True, exist_ok=True)
    dash = dashed_date(date)
    doc = {
        "page_title": f"ETF watchlist 원인 명확성 리포트 {dash}",
        "date": dash,
        "source_data": {
            "build_watchlist": build_status,
            "watchlist_db": str(watchlist_db),
            "definition": "score is cause clarity, not price prediction",
        },
        "items": rows,
        "sources": sorted({src for row in rows for src in row.get("sources", [])}),
    }
    json_path = reports_dir / f"watchlist_research_{dash}.json"
    md_path = reports_dir / f"watchlist_research_{dash}.md"
    json_path.write_text(json.dumps(doc, ensure_ascii=False, indent=2), encoding="utf-8")

    lines = [
        f"# ETF watchlist 원인 명확성 리포트 {dash}",
        "",
        "점수는 상승 확률이 아니라 원인 명확성 점수다.",
        "",
        f"- watchlist 종목 수: {len(rows)}",
        f"- build_watchlist: {build_status}",
        "",
    ]
    for row in sorted(rows, key=lambda r: (r["score"] or 0), reverse=True):
        lines += [
            f"## {row['name']} ({row['ticker']}) - {row['score']}점 / {row['category']}",
            f"- 종가: {row.get('close'):,}" if row.get("close") is not None else "- 종가: N/A",
            f"- 거래량 배율: {row.get('ratio')}" if row.get("ratio") is not None else "- 거래량 배율: N/A",
            f"- 원인 후보: {row['reason_summary']}",
            f"- {row['evidence_board']}",
            f"- {row['evidence_news']}",
            f"- {row['evidence_web']}",
            f"- 종합 의견: {row['final_opinion']}",
            "",
        ]
    md_path.write_text("\n".join(lines), encoding="utf-8")
    return json_path, md_path


def main() -> None:
    parser = argparse.ArgumentParser(description="Research generated watchlist stocks and score cause clarity")
    parser.add_argument("--date", help="target date YYYYMMDD or YYYY-MM-DD; default: latest watchlist date")
    parser.add_argument("--skip-build", action="store_true", help="do not run build_watchlist.py first")
    parser.add_argument("--force-build", action="store_true", help="pass --force to build_watchlist.py")
    parser.add_argument("--limit", type=int, help="smoke-test limit")
    args = parser.parse_args()

    watchlist_db, krx_db, reports_dir = load_paths()
    target_date = normalize_date(args.date)
    build_status = "skipped"
    built_target_date = None
    if not args.skip_build:
        built_target_date = run_build_watchlist(target_date, args.force_build)
        build_status = "success"
    if target_date is None:
        target_date = built_target_date or latest_watchlist_date(watchlist_db)

    tickers = load_watchlist(watchlist_db, target_date, args.limit)
    metrics = load_market_metrics(krx_db, watchlist_db, target_date, tickers)
    rows = []
    for ticker in tickers:
        try:
            rows.append(research_one(target_date, ticker, metrics.get(ticker, {})))
        except Exception as exc:
            name = ticker_name(ticker)
            rows.append(
                {
                    "date": dashed_date(target_date),
                    "ticker": ticker,
                    "name": name,
                    "ratio": metrics.get(ticker, {}).get("ratio"),
                    "today_volume": metrics.get(ticker, {}).get("today_volume"),
                    "avg5_volume": metrics.get(ticker, {}).get("avg5_volume"),
                    "trading_value": metrics.get(ticker, {}).get("trading_value"),
                    "close": metrics.get(ticker, {}).get("close"),
                    "score": 0,
                    "category": "조사 실패",
                    "reason_summary": f"종목 조사 중 오류: {exc}",
                    "final_opinion": "조사 실패로 원인 명확성 판단 불가.",
                    "evidence_board": "종토방: 조사 실패",
                    "evidence_news": "뉴스: 조사 실패",
                    "evidence_web": "웹: 조사 실패",
                    "sources": [f"https://finance.naver.com/item/board.naver?code={ticker}"],
                    "raw": {},
                }
            )

    upsert_scores(watchlist_db, rows)
    json_path, md_path = write_reports(reports_dir, target_date, rows, build_status, watchlist_db)
    print(f"[watchlist_research] date={target_date} rows={len(rows)}")
    print(f"[watchlist_research] upserted={watchlist_db}")
    print(f"[watchlist_research] json={json_path}")
    print(f"[watchlist_research] markdown={md_path}")


if __name__ == "__main__":
    main()
